name: GitHub Actions

on:  
  workflow_dispatch:
    
    inputs:
    name:
      description: 'Vorname'
      required: true

jobs:
  first:

    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo "Hello ${{ github.event.inputs.name }}"
      
