name: GitHub Actions

on:  
  workflow_dispatch:
    
    inputs:
    Vorname:
      description: 'Vorname'
      required: true
    
    Nachname:
      description: 'Nachname'
      required: false

jobs:
  First Job:

    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo "Hello ${{ github.event.inputs.Vorname }} ${{ github.event.inputs.Nachname }}"
      
