# GitHubActions.yml
name: GitHub Actions

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
       
      - name: Print
        run: | 
          echo "All"
          echo "${{ steps.files.outputs.all }}"
          
          echo "Added"
          echo "${{ steps.files.outputs.added }}"
          
          echo "Deleted"
          echo "${{ steps.files.outputs.deleted }}"
          
          echo "Renamed"
          echo "${{ steps.files.outputs.renamed }}"
          
          echo "Modified"
          echo "${{ steps.files.outputs.modified }}"

        
