# GitHubActions.yml
name: GitHub Actions

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  new:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.1.0
        id: files
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
       
      - name: Print
        run: echo "${{ steps.files.outputs.all }}"
